name: Continuous Integration

on: [push, pull_request]

env:
  NODE_VERSION: 18

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Run unit tests (Vitest)
        run: npm test:unit

      - name: Run e2e tests (Cypress)
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
