name: CI lint & tests

on: [push, pull_request]

env:
    NODE_VERSION: 16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ env.NODE_VERSION }}
            
      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
        
      - name: Run tests
        run: npm run test
